CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tasks_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE TASKS (
    id NUMBER PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_tasks_users FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE INDEX idx_tasks_user_id ON TASKS(user_id);

CREATE OR REPLACE TRIGGER users_bir BEFORE INSERT ON USERS FOR EACH ROW
BEGIN SELECT users_seq.NEXTVAL INTO :new.id FROM dual; END;
/

CREATE OR REPLACE TRIGGER tasks_bir BEFORE INSERT ON TASKS FOR EACH ROW
BEGIN SELECT tasks_seq.NEXTVAL INTO :new.id FROM dual; END;
/
